// examples/crx-solid/src/content-scripts/content.tsx
/* @refresh reload */
import { render } from 'solid-js/web';

import App from './App';


window.onload = async () => {
    const el = document.querySelector('body');
    if (el) {
      el.insertAdjacentHTML(
        'afterend',
        '<div id="crx-app"></div>',
      );
      render(() => <App />, document.getElementById('crx-app') as HTMLElement);
    }
}

// examples/crx-react/src/content-scripts/content.tsx
import ReactDOM from 'react-dom'
import App from './App'
import './content.css'

window.onload = async () => {
    const el = document.querySelector('body');
    if (el) {
      el.insertAdjacentHTML(
        'afterend',
        '<div id="crx-app"></div>',
      );
      ReactDOM.render(<App />, document.getElementById('crx-app') as HTMLElement);
    }
}
